spring.application.name=ralspotify_project
spring.datasource.url=jdbc:mysql://localhost:3306/ralspotify
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# spring.security.user.name=LucyAL
# spring.security.user.password=MaouSama11
jwt.secret=ALPH@E$7%Hg!k9Xy1pQa@8#bLm$T^Zu$R&V+J2pNcG5Dx8Fz!W@lPHA
jwt.expiration=3600000

# OAuth2.0 Authentication
spring.security.oauth2.client.registration.spotify.client-id=e985eb67d938484ba10f72657287bed6
spring.security.oauth2.client.registration.spotify.client-secret=8cc7f04024cc4acead6f5376e321ac8d
spring.security.oauth2.client.registration.spotify.scope=user-read-private,user-read-email,playlist-modify-public
spring.security.oauth2.client.registration.spotify.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spotify.redirect-uri=http://localhost:8080/login/oauth2/code/spotify

spring.security.oauth2.client.provider.spotify.authorization-uri=https://accounts.spotify.com/authorize
spring.security.oauth2.client.provider.spotify.token-uri=https://accounts.spotify.com/api/token
spring.security.oauth2.client.provider.spotify.user-info-uri=https://api.spotify.com/v1/me